Grossum\NewsBundle\Entity\News:
    type: mappedSuperclass
    table: news
    repositoryClass: Grossum\NewsBundle\Entity\Repository\NewsRepository
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        enabled:
            type: boolean
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        publicationAt:
            type: datetime
            nullable: false
            column: publication_at
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]