Grossum\NewsBundle\Entity\News:
    type: mappedSuperclass
    table: news
    repositoryClass: Grossum\NewsBundle\Entity\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
            options:
                unsigned: true
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        enabled:
            type: boolean
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        publicationAt:
            type: datetime
            nullable: false
            column: publication_at
    manyToOne:
        image:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            cascade:
                - persist
                - remove
    manyToMany:
        tags:
            targetEntity: Tag
            joinTable:
                name: news_to_tag
                joinColumns:
                    news_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]