Grossum\NewsBundle\Entity\Tag:
    type: mappedSuperclass
    table: tag
    repositoryClass: Grossum\NewsBundle\Entity\Repository\TagRepository
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    lifecycleCallbacks:
        prePersist: [setCreatedAtValue, setUpdatedAtValue]
        preUpdate: [setUpdatedAtValue]