services:
    sonata.admin.news:
        class: %grossum_news.admin.news.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Новости" }
        arguments:
            - ~
            - %grossum_news.entity.news.class%
            - ~

    sonata.admin.tag:
        class: %grossum_news.admin.news_tag.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Теги для новостей" }
        arguments:
            - ~
            - %grossum_news.entity.news_tag.class%
            - ~
        calls:
            - [ setNewsTagManager, [@grossum_news.tag.manager]]
