services:
    sonata.admin.news:
        class: Grossum\NewsBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Новости" }
        arguments:
            - ~
            - Grossum\NewsBundle\Entity\News
            - ~

    sonata.admin.tag:
        class: Grossum\NewsBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Теги для новостей" }
        arguments:
            - ~
            - Grossum\NewsBundle\Entity\Tag
            - ~
        calls:
            - [ setTagManager, [@grossum_news.tag.manager]]