services:
    sonata.admin.news:
        class: %grossum_news.news.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Новости" }
        arguments:
            - ~
            - %grossum_news.news.entity.class%
            - ~

    sonata.admin.tag:
        class: %grossum_news.tag.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: group.main, label: "Теги для новостей" }
        arguments:
            - ~
            - %grossum_news.tag.entity.class%
            - ~
        calls:
            - [ setTagManager, [@grossum_news.tag.manager]]