parameters:
    grossum_news.admin.news.class:              Grossum\NewsBundle\Admin\NewsAdmin
    grossum_news.admin.news_tag.class:          Grossum\NewsBundle\Admin\NewsTagAdmin
    grossum_news.entity.news.class:             Grossum\NewsBundle\Entity\BaseNews
    grossum_news.entity.news_tag.class:         Grossum\NewsBundle\Entity\BaseNewsTag
    grossum_news.entity_manager.news.class:     Grossum\NewsBundle\Entity\EntityManager\BaseNewsManager
    grossum_news.entity_manager.news_tag.class: Grossum\NewsBundle\Entity\EntityManager\BaseNewsTagManager
