<?php

namespace Grossum\NewsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findAllEnabledNewsOrderByPostedAt()
    {
        $query = $this->createQueryBuilder('news');

        $query
            ->where('news.enabled = :enabled')
            ->andWhere('post.postedAt <= :now')
            ->orderBy('post.postedAt', 'DESC')
            ->setParameters([
                'enabled' => true,
                'now'   => new \DateTime('now')
            ]);

        return $query->getQuery()->getResult();
    }

    public function findOneById($id)
    {
        return $this->findOneBy(['id' => $id]);
    }
}
